### ISSUE TITLE
input filter

### ISSUE THREAD

**Issue by anhackastro** [jamesaird/FAST#3]
What file should I input for FILTERS_RES? Should I use the master.FILTER.RES file in EAZY? If so, how can I add more filters to it and how should I make the translate file? Can I make my own FILTER.RES file? What is the format for that?

**Comment by jamesaird** [comment]
Apologies - the Filters directory had not ben included in the repository (this has now been fixed) which provides a number of filter specification files. 

But yes, the format is completely consistent with EAZY. To add new filters just follow the format in e.g.  FILTER.RES.v7.R300. Each filter is first specified by a line that specifies the number of wavelength entries (N) and then provides some information on the filter. The subsequent N lines then give a list of wavelength and transmission. Filters must be referenced by the number they occur in this list so it is also recommended to add an entry to FILTER.RES.v7.R300.info.txt
