### ISSUE TITLE
Cannot find ised_del.pr

### ISSUE THREAD

**Issue by Kincaidr** [jamesaird/FAST#5]
Hello,

I am trying to run FAST through IDL and I get the error:

```
Read parameter file: fast.param
% Compiled module: READCOL.
% Compiled module: REMCHAR.
% Compiled module: GETTOK.

           0
            ^
% Syntax error.

           0
            ^
% Syntax error.
% Compiled module: FAST_READ_FILTERS.
% Compiled module: ARRAY_INDICES.
% Compiled module: STRNUMBER.
% Compiled module: FAST_Z_ARR.
% Compiled module: PRIMES.
Make grid: co09_pr_del_ch_kc_936817_1041881/grid.save
% Compiled module: FAST_PRINT_GRID.

           0
            ^
% Syntax error.

           0
            ^
% Syntax error.
  Library:      Library unknown         
  SFH:          Delayed exponential SFH: SFR ~ t exp(-t/tau)  
  Stellar IMF:  Chabrier
  Dust law:     Kriek & Conroy (2013) average dust attenuation law
  metallicity:  0.0190
  log(tau/yr):  8.50   - 10.00, in steps of 0.50
  log(age/yr):  8.00   - 10.00, in steps of 0.20
  A_V:          0.00   -  3.00, in steps of 0.10
  z:            0.0100 -  6.0000, in steps of 0.0500
  Filters:      10  12  14  16  26  27  28
% Compiled module: FAST_LUM2FLUX.
% Compiled module: LUMDIST.
% Compiled module: COSMO_PARAM.
% Compiled module: QSIMP.
% Compiled module: ZPARCHECK.
% Compiled module: SETDEFAULTVALUE.
% Compiled module: TRAPZD.
% Compiled module: GALAGE.
% Compiled module: REPSTR.
    Read: co09_pr_ch_z019_ltau8.5.ised
ERROR:" Cannot find /home/astro/kincaid/Software/FAST_v1.0/Libraries/ised_del.pr/co09_pr_ch_z019_ltau8.5.ised
        Check path name, resolution and whether file exist
bash-4.2$ 
```
These are the external files I was told to get:

`ised_del.lr, ised_del.hr, ised_exp.hr, ised_tru.hr`

But I am not sure where to get `ised_del.pr`.

Thank you.

**Comment by guigui-99** [comment]
Hi Kincaidr, I'm encountering the same issue as you, did you end up finding where to download this file ?

**Comment by Kincaidr** [comment]
Hi @guigui-99. I encountered alot of problems using the IDL version. It would save you alot of trouble if you just used the python version (fastpp), its much simpler to install and run. I encountered no problems. Its also states that its 4x faster than this IDL version. Give it a try here:  https://github.com/cschreib/fastpp

**Comment by guigui-99** [comment]
Thank you for the fast reply, indeed I'm using fastpp already but as far as I understand it uses the same libraries as fast and it doesn't come with the ised_del.pr one so I was still trying to find it to use different SFH models in fastpp

**Comment by Kincaidr** [comment]
yes you are right. They use the same libraries. Its been a while since I installed, At which step of the installation are you getting this error?

**Comment by jamesaird** [comment]
I've added a link to download the ised_del.pr libraries, although it is up to you to choose which libraries to use (SFH, resolution etc.)
